version: '3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: true       # Enable WebSocket notifications.
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DOMAIN: ${DOMAIN}
      TZ: ${TZ}
    volumes:
      - ${DOCKERDIR}/appdata/vaultwarden:/data
    networks:
      - npm_proxy
    ports:
      - 280:80 # map 280 to any custom unused port (not 80)
networks:
  npm_proxy:
    external: true