version: '3'

services:
  db:
    image: postgres
    container_name: nextcloud_postgres
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=$PG_PWD
    networks:
      - npm_proxy
  
  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    command: redis-server --requirepass $REDIS_PWD
    restart: unless-stopped
    networks:
      - npm_proxy

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - $DOCKERDIR/appdata/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=nextcloud
      - POSTGRES_USER_FILE=nextcloud
      - POSTGRES_PASSWORD_FILE=$PG_PWD
      - REDIS_HOST_PASSWORD=$REDIS_PWD
    links:
      - db
      - redis
    networks:
      npm_proxy:
        ipv4_address: 192.168.89.251
    
volumes:
  db:
  nextcloud:
networks:
  npm_proxy:
    external: true
