version: '3'
services:
  portainer:
    container_name: portainer
    ports:
      - '8000:8000'
      - '9443:9443'
    restart: always
    volumes:
      - ${DOCKERDIR}/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    image: portainer/portainer-ce:latest
    environment:
      - TZ=${TZ}   
networks:
  default:
    external: true
    name: npm_proxy


