version: '3'
services:
  portainer:
    container_name: portainer
    ports:
      - '8000:8000'
      - '9443:9443'
    restart: always
    volumes:
      - '/home/docker/portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    image: portainer/portainer-ce:latest
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
    networks:
      - npm_proxy


